### ISSUE TITLE
`SchemaView.namespaces()` method doesn't handle expanded `prefixes` syntax

### ISSUE THREAD

**Issue by pkalita-lbl** [cmungall/linkml-runtime.js#3]
Currently `SchemaView.namespaces()` is only handling prefixes like:

```yaml
prefixes:
  linkml: https://w3id.org/linkml/
```

But it does not handle:

```yaml
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
```
